.TH WENDZELNNTPADM 8 "17 Apr 2021" ""
.\"=====================================================================
.SH "NAME"
wendzelnntpadm \- Newsgroup configuration tool for \fbwendzelnntpd (8)\fP.

.SH "SYNOPSIS"
\fBwendzelnntpadm\fP [options]

.SH "DESCRIPTION"
.B wendzelnntpadm
is used for managing the newsgroups, users and roles of
.B wendzelnntpd(8)\fP.

.\"=====================================================================
.SH OPTIONS
This version of \fBwendzelnntpadm\fP understands the following options.
.br
.br
.TP
.I
I. Newsgroup management commands:
.TP
.B listgroups
Lists all newsgroups of the database.
.TP
.BI addgroup \ grp \  [y/n]
Create the newsgroup
.I grp
in which posting is either allowed (
.I y
) or not (
.I
n
).
.TP
.BI delgroup \ grp
Delete the newsgroup
.I
grp.
.br
.br
.TP
.I
II. User management commands:
.TP
.B listusers
Lists all known users of a database.
.TP
.BI adduser \ usr \  [pw]
Create the user
.I
usr
with the password
.I
pw.
If the parameter
.I
pw
is not provided, it will be prompted.
.TP
.BI deluser \ usr
Delete the user
.I
usr
from the database.
.br
.br
.TP
.I
III. ACL (Access Control List) administration commands:
.br
.TP
.B listacl
List all ACL rules.
.TP
.BI addacluser \ usr \  grp
Add the user
.I
usr
to the newsgroup
.I
grp.
.TP
.BI delacluser \ usr \  grp
Remove the user
.I
usr
from the newsgroup
.I
grp.
.br
.br
.TP
.I
IV. Advanced role-based ACL (RBAC) commands:
.TP
.BI addaclrole \ rl
Create the ACL role
.I
rl.
.TP
.BI delaclrole \ rl
Remove the ACL role
.I
rl.
.TP
.BI rolegroupconnect \ rl \  grp
Link the role
.I rl
to the newsgroup
.I
grp.
.TP
.BI rolegroupunconnect \ rl \  grp
Unlink the role
.I
rl
from the newsgroup
.I
grp.
.TP
.BI roleuserconnect \ rl \  usr
Link the user
.I
usr
to the role
.I
rl.
.TP
.BI roleuserunconnect \ rl \  usr
Unlink the user
.I
usr
from the rl
.I
role.

.SH "WEBSITE"
\fIhttps://www.wendzel.de\fP
and
\fIhttps://cdpxe.github.io/WendzelNNTPd/\fP

.SH "AUTHOR"
WendzelNNTPd was developed by Steffen Wendzel.

.SH "BUGS"
Please send bug reports to  \fIsteffen@wendzel.de\fP.

.SH SEE ALSO
.BR wendzelnntpd (8)

