.TH WENDZELNNTPADM 8 "17 Apr 2021" ""
.\"=====================================================================
.SH "NAME"
wendzelnntpadm \- Newsgroup configuration tool for \fbwendzelnntpd (8)\fP.

.SH "SYNOPSIS"
\fBwendzelnntpadm\fP [options]

.SH "DESCRIPTION"
.B wendzelnntpadm
is used for managing the newsgroups, users and roles of
.B wendzelnntpd(8)\fP.

.\"=====================================================================
.SH OPTIONS
This version of \fBwendzelnntpadm\fP understands the following options.
.br
.br
.TP
.I
I. Newsgroup management commands:
.TP
.B listgroups
Lists all newsgroups of the database.
.TP
.BI addgroup \ newsgroup \  (y/n)
Create the newsgroup
.I newsgroup
in which posting is either allowed (
.I y
) or not (
.I
n
).
.TP
.BI delgroup \ newsgroup
Delete the newsgroup
.I
newsgroup.
.br
.br
.TP
.I
II. User management commands:
.TP
.B listusers
Lists all known users of a database.
.TP
.BI adduser \ username \  [password]
Create the user
.I
username.
If the parameter
.I
password
is not provided, it will be prompted.
.TP
.BI deluser \ username
Delete the user
.I
username
from the database.
.br
.br
.TP
.I
III. ACL (Access Control List) administration commands:
.br
.TP
.B listacl
List all ACL rules.
.TP
.BI addacluser \ username \  newsgroup
Add the user
.I
username
to the newsgroup
.I
newsgroup.
.TP
.BI delacluser \ username \  newsgroup
Remove the user
.I
username
from the newsgroup
.I
newsgroup.
.br
.br
.TP
.I
IV. Advanced role-based ACL (RBAC) commands:
.TP
.BI addaclrole \ role
Create the ACL role
.I
role.
.TP
.BI delaclrole \ role
Remove the ACL role
.I
role.
.TP
.BI rolegroupconnect \ role \  newsgroup
Link the role
.I role
to the newsgroup
.I
newsgroup.
.TP
.BI rolegroupunconnect \ role \  newsgroup
Unlink the role
.I
role
from the newsgroup
.I
newsgroup.
.TP
.BI roleuserconnect \ role \  username
Link the user
.I
username
to the role
.I
role.
.TP
.BI roleuserunconnect \ role \  username
Unlink the role
.I
username
from the role
.I
role.

.SH "WEBSITE"
\fIhttps://www.wendzel.de\fP
and
\fIhttps://cdpxe.github.io/WendzelNNTPd/\fP

.SH "AUTHOR"
WendzelNNTPd was developed by Steffen Wendzel.

.SH "BUGS"
Please send bug reports to  \fIsteffen@wendzel.de\fP.

.SH SEE ALSO
.BR wendzelnntpd (8)

