FROM debian:stable-slim

RUN apt-get update -y
RUN apt-get install -y gcc flex bison sqlite3 libsqlite3-dev mariadb-client libmariadb-dev-compat ca-certificates libmariadb-dev libmhash-dev make

RUN touch /var/log/wendzelnntpd

COPY .. /wendzelnntpd
WORKDIR /wendzelnntpd

RUN CONFFILE=wendzelnntpd_dev.conf ./configure
RUN make
RUN make install

ENTRYPOINT /usr/local/sbin/wendzelnntpd