FROM debian:stable-slim

RUN apt-get update -y
RUN apt-get install -y gcc flex bison sqlite3 libsqlite3-dev mariadb-client libmariadb-dev-compat ca-certificates libmariadb-dev libmhash-dev make

RUN touch /var/log/wendzelnntpd

COPY .. /wendzelnntpd
WORKDIR /wendzelnntpd

RUN mkdir -p /usr/local/etc/ssl
COPY ../server.crt /usr/local/etc/ssl/server.crt
COPY ../ca.crt /usr/local/etc/ssl/ca.crt
COPY ../server.key /usr/local/etc/ssl/server.key
COPY ../ca.crt /usr/local/share/ca-certificates

RUN update-ca-certificates

RUN CONFFILE=wendzelnntpd_dev.conf ./configure
RUN make
RUN make install

ENTRYPOINT /usr/local/sbin/wendzelnntpd