site_name: WendzelNNTPd Documentation
nav:
  - Introduction: index.md
  - Installation: install.md
  - Configuration: configuration.md
  - Running: running.md
  - Development: development.md
  - Upgrade: upgrade.md
theme: readthedocs
repo_url: https://github.com/cdpxe/WendzelNNTPd
edit_uri: edit/master/docs/docs/
copyright: GPLv3
markdown_extensions:
  - footnotes
