.TH WENDZELNNTPD 8 "17 Apr 2021" ""
.\"=====================================================================
.SH "NAME"
wendzelnntpd \- NTTP usenet server

.SH "SYNOPSIS"
\fBwendzelnntpd\fP [-d] [-h] [-v]

.SH "DESCRIPTION"
\fIwendzelnntpd\fP is an NTTP daemon tailored for easy configurability.

.SH OPTIONS
.TP
.B "\-d"
Start in daemon mode.
.TP
.B "\-h"
Print help output.
.TP
.B "\-v"
Output version information and exit.

.SH "ADMINISTRATION"
Administration of newsgroups is performed via 
.BR wendzelnntpadm (8)
and the configuration file
\fIwendzelnntpd.conf\fP.
.SH "WEBSITE"
\fIhttps://www.wendzel.de\fP
and
\fIhttps://cdpxe.github.io/WendzelNNTPd/\fP

.SH "AUTHORS"
WendzelNNTPd was originally developed by Steffen Wendzel. The development started in 2004. See the
.I
AUTHORS
file for a list of all contributors.

.SH "BUGS"
Please send bug reports to  \fIsteffen@wendzel.de\fP.

.SH SEE ALSO
.BR wendzelnntpadm (8)

