######################################################################
# Automatically generated by qmake (2.01a) Mo. Sep 21 12:54:40 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h ../../src/include/wendzelnntpdpath.h
SOURCES += gui.cpp
