set timeout 5

send_user "=== Test body command ===\n"

spawn telnet $env(nntp_address) 119

send_user "== Check response of body command without selected group ==\n"
send "body\n"
expect {
  timeout { send_user "Error: body command did not respond correctly\n"; exit 1 }
  -re "412 no news group current selected"
}

send_user "== Check response of body command without selected group with article number ==\n"
send "body 1\n"
expect {
  timeout { send_user "Error: body command did not respond correctly\n"; exit 1 }
  -re "412 no news group current selected"
}

send_user "== Check response of body command without selected group with existing message-id ==\n"
send "body <cdp1@localhost>\n"
expect {
  timeout { send_user "Error: body command did not respond correctly\n"; exit 1 }
  -re "412 no news group current selected"
}

send_user "== Check response of body command with empty group ==\n"
send "group alt.wendzelnntpd.test.empty\n"
send "body\n"
expect {
  timeout { send_user "Error: body command did not respond correctly\n"; exit 1 }
  -re "420 no \\(current\\) article selected"
}

send_user "== Check response of body command with non existing message-id ==\n"
send "body <1>\n"
expect {
  timeout { send_user "Error: body command did not respond correctly\n"; exit 1 }
  -re "430 no such article found"
}

send_user "== Check response of body command with non existing article number ==\n"
send "body 1\n"
expect {
  timeout { send_user "Error: body command did not respond correctly\n"; exit 1 }
  -re "430 no such article found"
}

send_user "== Check response of body command with group with article ==\n"
send "group alt.wendzelnntpd.test\n"
send "body\n"
expect {
  timeout { send_user "Error: body command did not respond correctly\n"; exit 1 }
  -re "222 1 <cdp1@localhost> article retrieved - body follows\\r\\nTest\\r\\n."
}

send_user "== Check response of body command with group with article with message-id ==\n"
send "group alt.wendzelnntpd.test\n"
send "body <cdp2@localhost>\n"
expect {
  timeout { send_user "Error: body command did not respond correctly\n"; exit 1 }
  -re "222 2 <cdp2@localhost> article retrieved - body follows\\r\\nTest2\\r\\n."
}

send_user "== Check response of body command with group with article with article number ==\n"
send "group alt.wendzelnntpd.test\n"
send "body 2\n"
expect {
  timeout { send_user "Error: body command did not respond correctly\n"; exit 1 }
  -re "222 2 <cdp2@localhost> article retrieved - body follows\\r\\nTest2\\r\\n."
}
