set timeout 2

send_user "=== Test xgtitle command ===\n"

spawn telnet $env(nntp_address) 119

send_user "== Check response of xgtitle command wihtout parameter ==\n"
send "xgtitle\n"
expect {
  timeout { send_user "Error: xgtitle command did not respond correctly\n"; exit 1 }
  -re "501 missing a parameter, see 'help'"
}

send_user "== Check response of xgtitle command with unknown wildmat parameter ==\n"
send "xgtitle invalid\n"
expect {
  timeout { send_user "Error: xgtitle command did not respond correctly\n"; exit 1 }
  -re "282 list of groups and descriptions follows\\r\\n\\."
}

send_user "== Check response of xgtitle command with wildmat parameter ==\n"
send "xgtitle .*wendzelnntpd.*\n"
expect {
  timeout { send_user "Error: xgtitle command did not respond correctly\n"; exit 1 }
  -re "282 list of groups and descriptions follows\\r\\nalt.wendzelnntpd.test -\\r\\nalt.wendzelnntpd.test.empty -\\r\\nalt.wendzelnntpd.test.post -\\r\\n\\."
}
