name: Test and publish Docker image

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  workflow_dispatch:

env:
    TEST_TAG: wendzelnntpd:test

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/wendzelnntpd
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./packages/docker/Dockerfile
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Install test tools
        run: sudo apt-get update -y && sudo apt-get install -y expect
      - name: Test
        run:  cd unittesting && ./test_dockerimage.sh ${{ env.TEST_TAG }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          context: .
          file: ./packages/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
